version: "3.8"

services:
  dolphinscheduler-postgresql:
    image: ${HUB}/bitnami/postgresql:15.2.0
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: dolphinscheduler
    volumes:
      - dolphinscheduler-postgresql:/bitnami/postgresql
    networks:
      - dolphinscheduler

  dolphinscheduler-zookeeper:
    image: ${HUB}/bitnami/zookeeper:3.7.1
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons
      ZOO_ENABLE_ADMIN_SERVER: "false"
      ZOO_ADMIN_SERVER_PORT_NUMBER: "0"
      ZOO_SERVER_ID: "1"
      ZOO_SERVERS: zookeeper0:2888:3888,zookeeper1:2888:3888,zookeeper2:2888:3888
    volumes:
      - dolphinscheduler-zookeeper:/bitnami/zookeeper
    extra_hosts:
      - "zookeeper0:10.209.250.10"
      - "zookeeper1:10.209.250.11"
      - "zookeeper2:10.209.250.12"
    network_mode: host

  dolphinscheduler-schema-initializer:
    image: ${HUB}/apache/dolphinscheduler-tools:${TAG}
    env_file: .env
    command: [ tools/bin/upgrade-schema.sh ]
    depends_on:
      - dolphinscheduler-postgresql
    volumes:
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - dolphinscheduler-shared-local:/opt/soft
      - dolphinscheduler-resource-local:/dolphinscheduler
    extra_hosts:
      - "postgresql:10.209.250.10"
    networks:
      - dolphinscheduler

  dolphinscheduler-api:
    image: ${HUB}/apache/dolphinscheduler-api:${TAG}
    ports:
      - "12345:12345"
      - "25333:25333"
    env_file: .env
    depends_on:
      - dolphinscheduler-zookeeper
    volumes:
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - dolphinscheduler-shared-local:/opt/soft
      - dolphinscheduler-resource-local:/dolphinscheduler
    extra_hosts:
      - "postgresql:10.209.250.10"
      - "zookeeper0:10.209.250.10"
      - "zookeeper1:10.209.250.11"
      - "zookeeper2:10.209.250.12"
    networks:
      - dolphinscheduler

  dolphinscheduler-alert:
    image: ${HUB}/apache/dolphinscheduler-alert-server:${TAG}
    env_file: .env
    depends_on:
      - dolphinscheduler-zookeeper
    volumes:
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
    extra_hosts:
      - "postgresql:10.209.250.10"
      - "zookeeper0:10.209.250.10"
      - "zookeeper1:10.209.250.11"
      - "zookeeper2:10.209.250.12"
    networks:
      - dolphinscheduler

  dolphinscheduler-master:
    image: ${HUB}/apache/dolphinscheduler-master:${TAG}
    env_file: .env
    depends_on:
      - dolphinscheduler-zookeeper
    volumes:
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - dolphinscheduler-shared-local:/opt/soft
    extra_hosts:
      - "postgresql:10.209.250.10"
      - "zookeeper0:10.209.250.10"
      - "zookeeper1:10.209.250.11"
      - "zookeeper2:10.209.250.12"
    networks:
      - dolphinscheduler

  dolphinscheduler-worker:
    image: ${HUB}/apache/dolphinscheduler-worker:${TAG}
    env_file: .env
    depends_on:
      - dolphinscheduler-zookeeper
    volumes:
      - dolphinscheduler-worker-data:/tmp/dolphinscheduler
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - dolphinscheduler-shared-local:/opt/soft
      - dolphinscheduler-resource-local:/dolphinscheduler
    extra_hosts:
      - "postgresql:10.209.250.10"
      - "zookeeper0:10.209.250.10"
      - "zookeeper1:10.209.250.11"
      - "zookeeper2:10.209.250.12"
    networks:
      - dolphinscheduler

networks:
  dolphinscheduler:
    driver: bridge

volumes:
  dolphinscheduler-postgresql:
  dolphinscheduler-zookeeper:
  dolphinscheduler-worker-data:
  dolphinscheduler-logs:
  dolphinscheduler-shared-local:
  dolphinscheduler-resource-local:
